### PR TITLE
Update projects.md

### PR DESCRIPTION
**Pull request by alex-taffe**
Update the projects.md file to be current as of March 7, 2018

### CODE REVIEW

**Comment by billdybas** [comment]
Can you also add a blurb about each project (like in Past Projects)?

**Comment by alex-taffe** [comment]
@billdybas updated

**Comment by billdybas** [comment]
FYI, when working off a fork, I suggest branching off of `devlop`, so you can pull in upstream changes to `devlop` and then rebase your branch off of `devlop`.

**Comment by alex-taffe** [comment]
Got it, thanks for the tip

**Pull request merged**
