### PR TITLE
Record SHA for issue #213

### PR DESCRIPTION
**Pull request by saf6260**
Adds shortened SHA for issue #213 so current version is displayed on footer of the website

### CODE REVIEW

**Comment by saf6260** [comment]
footersse
Here's what it currently looks like for the footer addition

**Comment by billdybas** [comment]
Thanks! I think you’ll also need to add it to our prod webpack config for it to show up on ssedev.se.rit.edu.

**Comment by billdybas** [comment]
I was curious if we'd have `git` available in Docker when we build our containers, and it looks like we do. One of the underlying images that `node:10` builds off installs `git`.

**Comment by wadeanthony0100** [comment]
Should we add an explicit dependancy on git in case of the unlikely event they remove their dependance?

**Comment by billdybas** [comment]
I wouldn't worry about it. I highly doubt they'd remove it from the official docker images. 

Gets added in [here](https://github.com/docker-library/buildpack-deps/blob/master/jessie/scm/Dockerfile). Hasn't been changed since 2015.

**Pull request merged**
