### PR TITLE
Add download icon for calendar events.

### PR DESCRIPTION
**Pull request by akath20**
Issue #214 

image

For some reason the link doesn't do anything in local dev, maybe since there are no events, but works fine in dev and prod.

### CODE REVIEW

**Comment by billdybas** [comment]
I wouldn't use the RSS icon as this isn't an RSS feed. This is an [iCalendar](https://en.wikipedia.org/wiki/ICalendar) file. Perhaps a calendar icon would make more sense.

Also, the link probably doesn't work in local dev because of how we proxy the API w/ traefik. We have a rule in eos that says any requests that match `https://{HOST}/api/v2` should go to the API instead of the frontend. No such rule exists in local development, so react router is picking up that route instead and will likely error because no frontend route for that exists.

**Comment by akath20** [comment]
I wasn’t sure about the RSS icon either... I just thought it would be more obvious it’s a link thank a calendar icon as people may just think it’s a UI nicety.

**Comment by billdybas** [comment]
You could make a button w/ a calendar icon inside w/ the text "Add to Calendar"

**Comment by akath20** [comment]
Updated. Still trying to fix alt text.
image

**Comment by akath20** [comment]
image

**Comment by akath20** [comment]
image

**Comment by akath20** [comment]
image

**Pull request merged**
