### PR TITLE
Fixed regression with committee names not showing up

### PR DESCRIPTION
**Pull request by vuzDylan**
Idk why all these commits are here I only made one.... weird

### CODE REVIEW

**Comment by vuzDylan** [comment]
We should also prob change the room number of the general meeting in this PR but I can't remember what the room number is

**Comment by billdybas** [comment]
The room # is 1520/1530. Also, extra commits might be a rebasing issue?

**Comment by vuzDylan** [comment]
ya i could be i'm not too sure

**Comment by vuzDylan** [comment]
I also tacked on the image size reduction issue to this PR because it was bothering me

**Pull request merged**
