### PR TITLE
Update Dockerfiles to run more lean

### PR DESCRIPTION
**Pull request by Tjzabel**
This PR improves the performance of building docker images from the given Dockerfiles. Furthermore, it tries to increase the readability, and sets better syntax standards.

### CODE REVIEW

**Comment by billdybas** [comment]
@akath20 If this looks good to you, looks good to me. @Tjzabel will need to rebase his changes when you rebase `devlop` b/c of #223.

**Comment by Tjzabel** [comment]
@billdybas there should be an option for you guys to update my branch through the GitHub interface near the Merge PR button area. 

If it's not there, then when I get home from work I'll be able to pull the new changes back into my branch.

**Comment by akath20** [comment]
@billdybas are there any issues using "rebase and merge" on the GitHub UI? Shouldn't it do the same thing? And @Tjzabel there is not an option to rebase from the UI.

**Comment by Tjzabel** [comment]
@billdybas heh, I usually do. I usually do PRs from within the same repo, so I don't often deal with forks. I'll keep that in mind in the future :+1:

**Comment by Tjzabel** [comment]
@billdybas @akath20 Branch is updated. Will make sure I create a new branch on future PRs :+1:

**Comment by billdybas** [comment]
@akath20 didn't rebase so your commit didn't do anything. 🤦‍♂️ 

No worries, I'll just merge and get things sorted out.

**Pull request merged**
