### PR TITLE
Upstream this to master 

### LINKED ISSUE #54: Favicon 404
Getting lots of 404 in traefik, should add that.

### PR DESCRIPTION
**Pull request by vuzDylan**
fixes overall mobile responsiveness
closes rit-sse/OneRepoToRuleThemAll#54

### CODE REVIEW

**Comment by 7imbrook** [comment]
@jcdesimp emails don't show up in the modal view when editing an officer.

**Comment by 7imbrook** [comment]
Also dark background on favicons

**Comment by vuzDylan** [comment]
What color dark you thinking?

**Comment by 7imbrook** [comment]
Adding an option on the committee drop down inside officer modal doesn't work.

**Comment by vuzDylan** [comment]
was that broken by this pr or has it always been broken

**Comment by vuzDylan** [comment]
because if this PR didn't break it that should be a separate issue

**Comment by 7imbrook** [comment]
ok let's fix before merge

**Comment by vuzDylan** [comment]
Can not reproduce just created two new committees from officers form

**Comment by 7imbrook** [comment]
Whelp. ok. Let's merge it

**Pull request merged**
