### PR TITLE
Fixes #67 Solution for #68

### LINKED ISSUE #67: Cannot add quotes to QDB
When trying to add new quotes to QDB, an update form appears and on submission, tries to update a quote that does not exist yet and a the quote is not added.

### PR DESCRIPTION
**Pull request by vuzDylan**

### CODE REVIEW

**Comment by vuzDylan** [comment]
#67 #68

**Comment by 7imbrook** [comment]
Whoops, added all my shit to this...

**Comment by vuzDylan** [comment]
....

**Comment by 7imbrook** [comment]
Can your stuff merge ok to prod?

**Comment by vuzDylan** [comment]
fixing atm

**Pull request closed without merging**
