### PR TITLE
Fix General Meeting Attempt #2

### PR DESCRIPTION
**Pull request by ss9415**
First PR was closed due to merging issues, this is an attempt to just blindly reopen it without making any changes to either base branch ("turn it off and back on"), to see if it works

### CODE REVIEW

**Comment by ss9415** [comment]
No conflict this time: hypothetically all this needs is approval

**Review by gavrielrh — APPROVED** [review]
👍

**Comment by gavrielrh** [comment]
If you need help resolving the conflicts, let me know :)

**Comment by ss9415** [comment]
image
I was wrong - we appear to have the same issue. There's commits on master that mirror commits on devlop (from the last PR that was rebased) and I think that's what it's complaining about: it's trying to rebase the same commits on top of themselves (I think at least, I haven't ever worked with rebasing before).

@gavrielrh I will pester you about this in a second.

**Pull request closed without merging**
