### PR TITLE
Opengraph data

### PR DESCRIPTION
**Pull request by jcdesimp**
This pull request adds openGraph data to the site. Making links from our site shared on Facebook and other sites that use OG look like this:
screen shot 2017-05-11 at 11 09 46 am

Without this change, they look like this:
screen shot 2017-05-10 at 6 52 16 pm

Edit:
Twitter card metadata has been added as well.

screen shot 2017-05-11 at 12 20 29 pm

### CODE REVIEW

**Comment by kristenmills** [comment]
Can we add the Twitter card tags? I think every where else that matters uses opengraph but for completeness sake, probably should add the Twitter ones.

**Comment by jcdesimp** [comment]
@kristenmills done.

screen shot 2017-05-11 at 12 20 29 pm

**Comment by kristenmills** [comment]
LGTM.  Since #66 is still a discussion, I'll let @7imbrook and @vuzDylan, decide whether to merge. I think it's worth doing, FWIW.

**Comment by 7imbrook** [comment]
For this small thing, that doesn't break dev, I think we can merge it. But we should avoid any future features that rely on that build environment variable.

**Pull request merged**
