### PR TITLE
Merge Upstream

### PR DESCRIPTION
**Pull request by billdybas**
🚀🚀🚀

### CODE REVIEW

**Comment by vuzDylan** [comment]
hella conflicts

**Comment by billdybas** [comment]
Pretty sure this is just because of the different histories. Didn't we run into the same issue the last time we pushed upstream?

**Comment by vuzDylan** [comment]
Ah ya it just needed a rebase
We always forget to rebase dev after we upstream

**Comment by vuzDylan** [comment]
I just don't understand why github can't do this...

**Comment by vuzDylan** [comment]
like all i did was type git rebase master

**Comment by vuzDylan** [comment]
I thought we weren't gonna use styled components though :alien:

**Comment by billdybas** [comment]
It's just on `Go` right now – some point in the next few months I want to do a full style overhaul. I like the workflow of `styled-components` but as we've mentioned before it does have a few shortcomings. Just want to switch to something that has Sass syntax but isn't Sass, and is scoped to components. I like having the styles co-located w/ components so you don't have to go searching around for them.

Some interesting discussion on Sass here: https://twitter.com/dan_abramov/status/952639729777954816

**Pull request merged**
