### PR TITLE
Update meeting time

### PR DESCRIPTION
**Pull request by wadeanthony0100**
The meeting time needs to be updated.

Also, prepush hooks are garbage, I had to remove them to push code that was already on devlop.

### CODE REVIEW

**Comment by wadeanthony0100** [comment]
I would argue that linting and other simple errors should be acceptable on a feature branch, but should be blocked from merge by build steps. Do we know how to set something like that up?

**Comment by akath20** [comment]
Looks good. This would be a first great test to see how to update the website.

**Comment by billdybas** [comment]
@wadeanthony0100 Probably could use GitHub [checks](https://help.github.com/articles/about-status-checks/#checks) or maybe [Danger JS](https://github.com/danger/danger-js). Possibly could also setup something in CircleCI which requires linting on PRs.

**Comment by billdybas** [comment]
@akath20 This will only deploy to devlop. You'll have to do another PR from devlop to master for it to deploy to `sse.rit.edu`. And then don't forget to rebase `devlop` off `master` (and force push up devlop).

**Pull request merged**
