### PR TITLE
MIT -> SSE

### PR DESCRIPTION
**Pull request by 7imbrook**
Made the license more SSE

### CODE REVIEW

**Comment by kristenmills** [comment]
Kek

**Comment by vuzDylan** [comment]
:whale: :whale2: :space_invader: :rocket:

**Comment by 7imbrook** [comment]
This issue hasn't been resolved

**Comment by vuzDylan** [comment]
This is cancer :cactus:

**Comment by 7imbrook** [comment]
Can we please keep this conversation civil

**Comment by vuzDylan** [comment]
Best

**Comment by vuzDylan** [comment]
Forever love

**Comment by billdybas** [comment]
Welp... ✌🏻

**Pull request closed without merging**
