### PR TITLE
Logical directory structure

### PR DESCRIPTION
**Pull request by vuzDylan**
This file structure makes a lot more sense and is way less repetitive :rocket:

### CODE REVIEW

**Comment by vuzDylan** [comment]
Oh man it also makes the application 2.21 kb smaller :whale2:

**Comment by kristenmills** [comment]
Though I'd change general to common. Since general was a bad name to begin with

**Comment by vuzDylan** [comment]
Oh yes this would be much better thanks bra

**Comment by vuzDylan** [comment]
and for the record I knew this was better but it was just so much work

**Comment by vuzDylan** [comment]
oh boy grep | xargs sed FTW

**Pull request merged**
